### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [LucasHild/mcp-server-bigquery#2]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/bgkxh59h9w) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.13

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/LucasHild/mcp-server-bigquery .



RUN uv sync

CMD ["uv", "run", "mcp-server-bigquery"]
```

When I run it, I get the following error:

```
2024-12-25 15:36:03,222 - mcp_bigquery_server - INFO - Starting MCP BigQuery Server
2024-12-25 15:36:03,223 - mcp_bigquery_server - INFO - Starting BigQuery MCP Server with project: None and location: None
Traceback (most recent call last):
  File "/app/.venv/bin/mcp-server-bigquery", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/app/src/mcp_server_bigquery/__init__.py", line 14, in main
    asyncio.run(server.main(args.project, args.location, datasets_filter))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/app/src/mcp_server_bigquery/server.py", line 100, in main
    db = BigQueryDatabase(project, location, datasets_filter)
  File "/app/src/mcp_server_bigquery/server.py", line 32, in __init__
    raise ValueError("Project is required")
ValueError: Project is required

```

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

I believe the issue here is that documentation does not describe every environment variable that's needed to start the server.

Could you provide a complete example in the README showing how to start the server using `uv run`?

This would improve usability for developers and help automated systems like [Glama](https://glama.ai/mcp/servers) to test the server

**Comment by LucasHild** [comment]
Hey @punkpeye, to configure the server, you would need to pass the argument `--project` and `--location` (see [README](https://github.com/LucasHild/mcp-server-bigquery/blob/main/README.md#configuration)):

```
CMD ["uv", "run", "mcp-server-bigquery", "--project", "...", "--location", "..."]
```

For now, this server can't be configured with environment variables. Do you see any advantages of using environment variables over arguments?

**Comment by punkpeye** [comment]
From security perspective, when talking about hosted MCP servers, I would not want any configuration to be passed in a way that can get logged.

**Comment by LucasHild** [comment]
I added support for environment variables: https://github.com/LucasHild/mcp-server-bigquery/pull/14
